# Generated by Django 5.2.17 on 2026-09-14 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#e74c3c",
                        help_text="Color hex usado en el mapa (ej: #e74c3c)",
                        max_length=7,
                    ),
                ),
                ("thingspeak_channel_id", models.CharField(blank=True, max_length=20)),
                (
                    "thingspeak_read_api_key",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "thingspeak_write_api_key",
                    models.CharField(blank=True, max_length=64),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Parada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("orden", models.PositiveSmallIntegerField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("texto_pantalla", models.CharField(max_length=64)),
                (
                    "audio_track",
                    models.CharField(
                        help_text="Pista en la SD del DFPlayer (ej: 001.mp3)",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionDispositivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volumen", models.PositiveSmallIntegerField(default=20)),
                (
                    "texto_default",
                    models.CharField(default="LINEA 102 - VIXEL", max_length=64),
                ),
                ("radio_deteccion_parada_m", models.PositiveIntegerField(default=30)),
                ("intervalo_subida_s", models.PositiveIntegerField(default=15)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispositivo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion",
                        to="flota.dispositivo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Viaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        choices=[("ida", "Ida"), ("vuelta", "Vuelta")], max_length=10
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fin", models.DateTimeField(blank=True, null=True)),
                ("distancia_km", models.FloatField(default=0)),
                ("velocidad_media_kmh", models.FloatField(default=0)),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajes",
                        to="flota.dispositivo",
                    ),
                ),
            ],
            options={
                "ordering": ["-inicio"],
            },
        ),
        migrations.CreateModel(
            name="Desvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("momento", models.DateTimeField()),
                ("distancia_m", models.FloatField()),
                (
                    "viaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desvios",
                        to="flota.viaje",
                    ),
                ),
            ],
            options={
                "ordering": ["momento"],
            },
        ),
        migrations.CreateModel(
            name="Posicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("hdop", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(help_text="Momento del fix GPS")),
                (
                    "bytes_enviados",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "bytes_recibidos",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "reportes_enviados",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("uptime_s", models.PositiveIntegerField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posiciones",
                        to="flota.dispositivo",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["dispositivo", "-timestamp"],
                        name="flota_posic_disposi_b9cb9a_idx",
                    )
                ],
            },
        ),
    ]
