# Generated by Django 5.2.17 on 2026-09-17 01:35

import flota.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositivo",
            name="device_key",
            field=models.CharField(
                default=flota.models.generar_device_key,
                editable=False,
                help_text="Credencial del dispositivo fisico. Se regenera desde una accion del admin.",
                max_length=64,
                unique=True,
            ),
        ),
    ]
