# Generated by Django 5.2.17 on 2026-09-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota", "0002_dispositivo_device_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Linea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "terminal1_nombre",
                    models.CharField(default="Terminal 1", max_length=100),
                ),
                ("terminal1_lat", models.FloatField(blank=True, null=True)),
                ("terminal1_lon", models.FloatField(blank=True, null=True)),
                (
                    "terminal2_nombre",
                    models.CharField(default="Terminal 2", max_length=100),
                ),
                ("terminal2_lat", models.FloatField(blank=True, null=True)),
                ("terminal2_lon", models.FloatField(blank=True, null=True)),
                (
                    "ruta_ida",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de puntos [lat, lon] del recorrido de ida",
                    ),
                ),
                (
                    "ruta_vuelta",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de puntos [lat, lon] del recorrido de vuelta",
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
